#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m zptool --dbase $HOME/zptess/zptess.db --log-file $HOME/zptess/zptool.log batch end $*
