#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m zptool -d $HOME/zptess/zptess.db -l $HOME/zptess/zptool.log summary export --updated --csv-file $HOME/zptess/summary_all.csv $*
