#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m zptool --dbase zptess.db --log-file zptool.log batch export --email --updated True --latest --base-dir /tmp/zptool $*
