#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m zptess -c -d $HOME/zptess/zptess.db -l $HOME/zptess/zptess.log -rO -tM tas -S 75 -tE serial:1 $*

