#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m zptess --console --dbase zptess.db --log-file zptess.log --model tas --rounds 5 --samples 75 --port serial:1 $*
