#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python3 -m zptess --console --dbase zptess/zptess.db --log-file zptess/zptess.log --model tess-w --old-protocol --rounds 5 --samples 125 $*
