#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m zptess --console --dbase zptess.db --log-file zptess.log --model tess-w --ref-old-protocol --rounds 5 --samples 125 $*
